### ISSUE TITLE
where do i find the code for the working example ?

### ISSUE THREAD

**Issue by Davidriquelme** [officert/vue-slideout-panel#10]
where do i find the code for the working example ?

**Comment by officert** [comment]
hey @Davidriquelme, in the example, https://officert.github.io/vue-slideout-panel/#/home, you can find snippets for using Vue Slideout Panel. Let me know if that's not enough though, happy to either update the docs or provide more info. 👍

**Comment by Davidriquelme** [comment]
thanks!, it will be great if you can provide the working example from the demo, if you could.

**Comment by officert** [comment]
All of the code for the demo can be found here : https://github.com/officert/vue-slideout-panel/tree/master/docs-src/components

The `Home` component is the Home page of the demo site : https://github.com/officert/vue-slideout-panel/blob/master/docs-src/components/Home/index.vue
