### ISSUE TITLE
main panel height

### ISSUE THREAD

**Issue by Davidriquelme** [officert/vue-slideout-panel#12]
@officert is it possible to set a custom height to this div ? maybe adding this option via prop ?

![image](https://user-images.githubusercontent.com/12628676/44034590-d81c6ea8-9ee3-11e8-9dc6-08adaf244bf3.png)

**Comment by officert** [comment]
We could add that, but I'm curious what you're use case is?

**Comment by officert** [comment]
Closing, not enough info
