### ISSUE TITLE
Use with Single File Components

### ISSUE THREAD

**Issue by davidAlittle** [officert/vue-slideout-panel#14]
Having issues showing SFC's in panel. 

```
import LSP from './LineSpeedPane.vue';
import {vueSlideoutPanelService} from 'vue2-slideout-panel';
export default {
    components: {
        'linespeedpane': LSP,
    },
...
    methods: {
        showPanel() {
                vueSlideoutPanelService.show({
                        component: 'linespeedpane',
                        width: '500px',
                        props: {}
                    })
                    .then(result => {

                    });
            },
```

In LineSpeedPane.vue I've made sure to set the `name: 'linespeedpane'` property, if that matters (the fault thrown seems to suggest it might): `[Vue warn]: Unknown custom element: <linespeedpane> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Do I have to globally register the component I want to embed?

**Comment by officert** [comment]
I believe it needs to be a globally registered component. It's just using Vue's `<component>` element : https://vuejs.org/v2/guide/components.html#Dynamic-Components

**Comment by davidAlittle** [comment]
Globally registering does work.

**Comment by francoism90** [comment]
@officert I know this is an old ticket, but would it be an option to add support for local components? It did work fine in V1.

Thanks. :)

**Comment by officert** [comment]
@francoism90 I think you can pass in the actually component object:

```
import LSP from './LineSpeedPane.vue';

vueSlideoutPanelService.show({
                        component: LSP,
                        width: '500px',
                        props: {}
                    });
```

Let me know if not, I can look into it some more.

**Comment by spocock** [comment]
I can confirm it does work as described with the component object

````
 import Slideup from '~/components/Slideup';
  ...
  methods: {
    showPanel() {
      const panel = this.$showPanel({
        component: Slideup,
        ...
      });
    },
````
