### ISSUE TITLE
It is possible to keep alive the content of the vueSlideoutPanelService?

### ISSUE THREAD

**Issue by andresinostroza** [officert/vue-slideout-panel#15]
I am trying to figure how to keep alive the content here:

![image](https://user-images.githubusercontent.com/18563082/44308837-17242480-a400-11e8-89fc-e0be3aa1caea.png)

It is possible? or the component need to be created each time?

**Comment by andresinostroza** [comment]
Please, I am trying to keep alive the component because I have some filters on it, so I don't want to lose the data there, I can use vuex I know, or even I can send the filters again, but is not the idea, if you need some help, I can help you as well

**Comment by Dwa1n** [comment]
@officert - Appreciate the work done so far on this... Great UI component! These three additions to this package would make it perfect for me:

1. `<keep-alive>`
2. `<slot>`
3. `.sync` on props

**Comment by Dwa1n** [comment]
@officert A colleague of mine pointed me to this package [vue-slideout-panel](https://github.com/lyollix/vue-slideout-panel). Not sure if it could be useful inspiration for this package.

**Comment by officert** [comment]
@Dwa1n and @andresinostroza sorry for the delay, but I just release V1.0.0 which now supports `keep-alive`:

https://github.com/officert/vue-slideout-panel/releases/tag/1.0.0

**Comment by officert** [comment]
^ be sure to check out the docs for this release as it has breaking changes.
With this release you can also now programmatically show and hide panels from your outer code.

**Comment by officert** [comment]
Closing this issue.

For `<slots>` support, follow on this ticket : https://github.com/officert/vue-slideout-panel/issues/13

For `.sync` support, follow on this ticket : https://github.com/officert/vue-slideout-panel/issues/19
