### ISSUE TITLE
cssClass not working

### ISSUE THREAD

**Issue by davidAlittle** [officert/vue-slideout-panel#16]
No matter how or where I put the class, cssClass attributes never get applied. Are you sure this works?

**Comment by officert** [comment]
Can you share your code? It's working on the demo page:
```
vueSlideoutPanelService.show({
          component: 'panel-1',
          width: '500px', //customize the width
          cssClass: 'panel-1-custom-class', //add a custom CSS class
          props: {
            data: {
              firstName: 'John',
              lastName: 'Doe',
              age: 39
            }
          }
        })
        .then(results => {
          console.log('Results for panel 1:', results);
        });
```

**Comment by officert** [comment]
Closing for now, re-open with your code sample

**Comment by ryantzor** [comment]
I have an issue with CSS as well. My code is like the below example:

- somefile.vue
<script>
`vueSlideoutPanelService.show({
          component: 'slide-out-panel-2',
          cssClass: 'slide-out-panel-2-custom',
          width: '300px',
          props: {
            isEditMode: true,
            property: index
          }
        })`
</script>
<style>
.slide-out-panel-2-custom {
 // stuff here
}
</style>

**Comment by officert** [comment]
@ryantzor which version of the library are you using? Might be an old version with a bug. Take a look at this example, it's working here:

https://vue2-slideout-panel.wrkflows.io/en/articles/1006

**Comment by ryantzor** [comment]
Hey man, thanks for the reply. I have to update my vue version to get this installed it looks like. I'll revisit this later and let you know if I still have issues. My current version in package .json says ^0.4.0

**Comment by spocock** [comment]
I had this issue when I accidentally placed the class definition within a scoped style section https://vue-loader.vuejs.org/guide/scoped-css.html. It worked fine when I moved the class to a global style.
