### ISSUE TITLE
Proper way to catch slideout's close event?

### ISSUE THREAD

**Issue by zaiste** [officert/vue-slideout-panel#17]
What would be the proper way to handle the close event ? It looks like each layer has its own identifier attached to `hideSlideOutPanel`, but I don't see how to access it.

**Comment by officert** [comment]
`slideoutPanelService.show()` will return a `Promise`, which will be resolved when the panel is closed. So you can handle the close event like this:

``` js
slideoutPanelService.show()
  .then(result => {
      console.log('panel is closed')
  });
```

Let me know if that's what you meant. Currently there is no way to programmatically close a panel from the code that calls `slideoutPanelService.show()`.

**Comment by zaiste** [comment]
@officert Thanks for the fast response. Yes, that's it. I wasn't sure about this approach. I thought I missed some events etc. It's clear now!
