### ISSUE TITLE
Prevent Close on Background Click

### ISSUE THREAD

**Issue by wontwon** [officert/vue-slideout-panel#18]
Hello, I was wondering if you were thinking of adding a prop to prevent panel from closing when clicking the background.

**Comment by officert** [comment]
Added in V0.13.0 : https://github.com/officert/vue-slideout-panel/releases/tag/0.13.0

**Comment by wontwon** [comment]
Hey @officert, I updated to version 0.13.0 and passed disableBgClick, but clicking on the bg still closed the panel. 

Please see the gif below:
![2018-08-22 23 56 13](https://user-images.githubusercontent.com/3239936/44504008-4f796c00-a667-11e8-81c3-9416cedb8dbb.gif)


` vueSlideoutPanelService.show({
          width: 600,
          cssClass: "event-detail-container",
          component: 'event-category-panel',
          disableBgClick: true,
          props: {
            showEventTimePanel: this.showEventTimePanel
          }
        })
          .then(result => {
            console.log(result)
          })`

**Comment by wontwon** [comment]
Disregard last comment. Thanks for the fix!
