### ISSUE TITLE
style examples, controlling height?

### ISSUE THREAD

**Issue by easherma** [officert/vue-slideout-panel#2]
What is the best way to override styles for the panel, say if we wanted to set height or background color?

**Comment by KingLagalot** [comment]
Also wondering this, can't get the width to change, its set to 900px and I can't seem to override it.

**Comment by officert** [comment]
@KingLagalot found a bug with that. Setting the width using `900` worked, but using `900px` didn't. Fixed in V0.5.0 : https://github.com/officert/vue-slideout-panel/releases/tag/0.5.0

**Comment by officert** [comment]
@easherma good call, didn't support that before, but just added support for it in V0.6.0:
https://github.com/officert/vue-slideout-panel/releases/tag/0.6.0
