### ISSUE TITLE
Pass component object instead of component name

### ISSUE THREAD

**Issue by ajerez** [officert/vue-slideout-panel#20]
In older versions of the library you can pass the component object instead of the component "name", but now we need to register our components globally before we can use the panel passing our component "name" to it.

There is any chance the API can work with both options so we can not register our components inside the panel globally?

Thanks for all

**Comment by officert** [comment]
thanks @ajerez fixed in V1.0.3 : https://github.com/officert/vue-slideout-panel/releases/tag/1.0.3
