### ISSUE TITLE
Vuetify Autocomplete does not close

### ISSUE THREAD

**Issue by saranshinvy** [officert/vue-slideout-panel#22]
When using vuetify component inside the panel you cannot close the list by clicking outside, also my website is scrollable and when i use the slideout panel the main site scroll is not hidden , is this bug?

**Comment by officert** [comment]
@saranshinvy could you fork this Code Pen (https://codepen.io/tofficer/pen/JaxNdw) and try and recreate your issue? Hard to help without some more info on what's going on.

**Comment by officert** [comment]
Closing this. Please re-open if you can provide some more info.

**Comment by husstahn** [comment]
This is an issue on Buefy too. Dropdown / autocomplete does not close on blur. This really needs to be addressed if anyone intends to use slideout for forms.
