### ISSUE TITLE
Error with removing class

### ISSUE THREAD

**Issue by ChadTaljaardt** [officert/vue-slideout-panel#25]
Hello, 

I'm having a issue with this plugin on my app which integrates this plugin alongside modals. When i use the slideout, i cannot use the modals anymore. 

I see that we add a specific style of class depending on if there is other classes on the body. 

https://github.com/officert/vue-slideout-panel/blob/937df7d2afa8306025f17129bb0d936ada421d06/src/components/SlideoutPanel/index.vue#L158

The issue (i think) but dont understand why, is that when we remove the class, it leaves 
```
class=" " 
```

because of this function:

https://github.com/officert/vue-slideout-panel/blob/937df7d2afa8306025f17129bb0d936ada421d06/src/components/SlideoutPanel/index.vue#L163

**Comment by officert** [comment]
@ChadTaljaardt can you try v1.0.6?

https://github.com/officert/vue-slideout-panel/releases/tag/1.0.6

**Comment by ChadTaljaardt** [comment]
@officert Hello, 

I am trying to use the release that you tagged, but now im getting the same issue as listed here https://github.com/officert/vue-slideout-panel/issues/24#issuecomment-436415385

I am unable to test the fix as a result until that other issue is resolved.

**Comment by officert** [comment]
@ChadTaljaardt I fixed this issue in V2.0.0 as well as some issues with installing the component:

https://github.com/officert/vue-slideout-panel/releases/tag/2.0.0

**Comment by kruteev** [comment]
I get this error on 2.4.0 version
<img width="1913" alt="Снимок экрана 2019-10-14 в 16 43 41" src="https://user-images.githubusercontent.com/5311779/66757375-baf24e80-eea4-11e9-8a9c-e0afa0090ff6.png">

**Comment by officert** [comment]
@kruteev are you sure that's caused by this component?
