### ISSUE TITLE
Setting hideBg: true forces disableBgClick: true ?

### ISSUE THREAD

**Issue by dmcdonald8** [officert/vue-slideout-panel#28]
I don't want the background to darken when I have the slideout panel open so I set `hideBg: true`
However, now when I click outside the panel it doesn't close itself as it used to when the background was visible. Looks like I'd need to add some kind of close button, myself.

Would be great to still have the same functionality of clicking outside the modal without the dark background. If the bg was still there but not darkened that would be fine for me, maybe an option for this is possible?

**Comment by officert** [comment]
thanks for the suggestion @dmcdonald8, I just release v2.1.0 and made that change:

https://github.com/officert/vue-slideout-panel/releases/tag/2.1.0
