### ISSUE TITLE
Add support for multiple panels (with keepAlive=true)

### ISSUE THREAD

**Issue by tuomas2** [officert/vue-slideout-panel#30]
Currently, if you have multiple panels that have keepAlive=True and if you close panel by emitting 'closePanel' from panel component code, it won't work properly for all the panels created. It looks it works only for one panel.

If keepAlive=false, everything works OK.

**Comment by officert** [comment]
Maybe I'm misunderstanding you, but I think this is the intended behavior. Emitting `closePanel` from the component code is meant to close the top most panel only.

**Comment by tuomas2** [comment]
In our codebase it is not even possible to have 2 panels open at the same time.

Let's say you have 2 panels. Each of them have 'close' button, which emits closePanel and all of them are keepAlive=true.

1. Open second panel. -> ok
2. Close second panel. -> ok
3. Open first panel. -> ok
4. Close first panel -> nok, does not work.

(steps 1 & 2 are not necessary, only the second panel close button works because closePanel tries to close second panel even when triggered from first panel). 

My PR #31 fixes this.

**Comment by officert** [comment]
Can you reproduce this in a CodePen or JsFiddle? Here's a CodePen you can fork:

https://codepen.io/officert/pen/rPbWNb
