### ISSUE TITLE
Add support for opening on the bottom like Material Design "bottom sheets"

### ISSUE THREAD

**Issue by seanhudson** [officert/vue-slideout-panel#32]
Would it be possible to add a bottom open option to have the panels behave like a "bottom sheet?"

Like https://material.io/develop/android/components/bottom-sheet-behavior/

**Comment by officert** [comment]
Just added in `v2.2.2`:

https://github.com/officert/vue-slideout-panel/releases/tag/2.2.2

https://vue2-slideout-panel.wrkflows.io/en/articles/1003

Good suggestion! 👍

**Comment by seanhudson** [comment]
Tim, thank you!
