### ISSUE TITLE
TypeError: Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by thukuwanjiku** [officert/vue-slideout-panel#33]
I'm getting this error and the panel does not slideout.

Here are shots of my code, please help

![vue](https://user-images.githubusercontent.com/17809323/53686716-c2148400-3d3b-11e9-919d-2b3485ddaa20.PNG)
![slideout](https://user-images.githubusercontent.com/17809323/53686686-4ca8b380-3d3b-11e9-8ae8-48f1ce8524be.PNG)

**Comment by officert** [comment]
Upgrade to the latest version, and use `this.$showPanel()`. 

https://vue2-slideout-panel.wrkflows.io/en/articles/1003

**Comment by thukuwanjiku** [comment]
@officert your link helped. It's working all fine now. Thanks big time!

**Comment by riyaz51** [comment]
![showPanel](https://user-images.githubusercontent.com/43986917/57567668-7eed2600-73fa-11e9-9087-aee074c03ebe.JPG)

**Comment by riyaz51** [comment]
Hello, I'm getting the  "this.$showPanel is not a function" error. How to resolve this?

**Comment by officert** [comment]
@raj5152 which version are you using?

**Comment by thukuwanjiku** [comment]
> Upgrade to the latest version, and use `this.$showPanel()`.
> 
> https://vue2-slideout-panel.wrkflows.io/en/articles/1003

@officert using this method you referenced here, how can listen to the close event of the panel? I tried adding `.then()` to the `showPanel()` as you suggested [here](https://github.com/officert/vue-slideout-panel/issues/17#issuecomment-414739407) 

![image](https://user-images.githubusercontent.com/17809323/61866091-3c0cfb80-aedd-11e9-9f52-e786085bf604.png)


but it gives the error, 

![image](https://user-images.githubusercontent.com/17809323/61866038-1849b580-aedd-11e9-94a8-9940033794d0.png)
