### ISSUE TITLE
Add support for toggle show/hide panel

### ISSUE THREAD

**Issue by seanhudson** [officert/vue-slideout-panel#35]
Right now if you click the trigger for a panel multiple times, it will open additional panels right on top of each other. This has already confused some users, and it's not really the expected behavior the panels should have.

One option may be to toggle the panel closed if the trigger clicked again after opening. The second would be to just ignore the trigger if clicked again.

**Comment by ChadTaljaardt** [comment]
I have noticed this in my application as well.

**Comment by officert** [comment]
Can someone post a CodePen or JSFiddle that shows how this is happening? I can't reproduce this.

**Comment by seanhudson** [comment]
This is a crude example, and it's just one of several similar type experiences on my app.

https://codepen.io/crowandraven/pen/VNyKoK

In reality, there could be any number of triggers (usually in the form of icons). A few could be hamburger for mobile navigation, plus icon to add new content, etc. 

Ideally, clicking the trigger would toggle the panel. This is the behavior used on many UI that utilize drawers and panels. Instead, it just spawns another panel. If someone expects to close the panel by toggling, they instead get 5 more panels on top of each other.

So, ideally, this package would include a toggle method that would work universally to beat this issue.

**Comment by seanhudson** [comment]
@officert did that example make sense to you? I can't quite figure out the best way to have a toggle to resolve this issue.

**Comment by officert** [comment]
@seanhudson thank you for the example. You can achieve the desired effect by holding onto the `panelInstance` returned from `$showPanel()` and calling `hide()` on it to hide the panel. 

```js
showPanel() {
      if (this.panelInstance) {
        this.panelInstance.hide();

        delete this.panelInstance;
      } else {
        this.panelInstance = this.$showPanel({
          component: "panel-1",
          cssClass: "panel-1",
          props: {}
        });

        this.panelInstance.promise.then(() => {
          delete this.panelInstance;
        });
      }
    }
```

https://codepen.io/officert/pen/OGZBxR
