### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by eduardoluizm** [officert/vue-slideout-panel#36]
Hello,

I add this component on packages.json and after import and use, i generated my js files with webpack. I have a small project and my "vendors.js" jumped to 450k+- minified, instead 96kb (vuejs and some utils).

If I open dist folder on github the vue2-slideout-panel.js has more than 300kb..

There is a way to merge it on my webpack, to make it smaller?

**Comment by officert** [comment]
Vue by itself takes up 290KB:

![Uploading Screen Shot 2019-06-02 at 8.57.00 AM.png…]()
