### ISSUE TITLE
Nuxt

### ISSUE THREAD

**Issue by Kohlibrie** [officert/vue-slideout-panel#4]
How to use your plugin with nuxt?

I added it to my plugins and to to nuxt.config.js like

```
plugins: [
 {src: '~/plugins/vue2-slideout-panel', ssr: false}
]
```

**Comment by officert** [comment]
I'm not very familiar with Nuxt.js, but I found this page https://nuxtjs.org/guide/plugins/ describing how to use Vue.js plugins with it.

I believe you would need to create a new file under your `plugins` directory, like this (plugins/vue2-slideout-panel.js):

```js
import Vue from 'vue';
import {
  VueSlideoutPanel
} from 'vue2-slideout-panel';

Vue.component('slideOutPanel', VueSlideoutPanel);
```

and then your nuxt.config.js file should work.

Let me know how that goes.

**Comment by girardinsamuel** [comment]
Hello,

Did you find a solution finally ? Is the plugin-way proposed by @officert is working ?
I tried on my side but I get the following error 
`NuxtServerError: render function or template not defined in component: anonymous`

**Comment by jenil** [comment]
I can confirm it doesn't work with Nuxt.

**Comment by officert** [comment]
I don't know how Nuxt works, so if someone who does wants to submit a PR I'm happy to take a look. If I have some time to learn a bit more about Nuxt at some point I can take a crack, but can't guarantee anything soon.

**Comment by jenil** [comment]
Here is a sample app

https://glitch.com/edit/#!/gelatinous-wizard

**Comment by jenil** [comment]
From some quick debugging it appears to be an issue concerning the Webpack packing of the bundle.

This doesn't work in a Nuxt project:
```
import {
  VueSlideoutPanel
} from 'vue2-slideout-panel';
```
`VueSlideoutPanel` is `undefined`

**Comment by officert** [comment]
closing for now, submit a PR if you have a solution 👍
