### ISSUE TITLE
How to pass component? 

### ISSUE THREAD

**Issue by Tropicalista** [officert/vue-slideout-panel#41]
In a freshly created vue cli project I got this error:

`Unknown custom element: <dashboard> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

I followed the example on the docs.

Can you put me on the right direction?

**Comment by officert** [comment]
Sounds like you don't have your `dashboard` component registered with Vue. You'll need something like 

```js
import Dashboard from 'components/Dashboard';

Vue.component({
  components: {
     Dashboard
  }
});
``

**Comment by Tropicalista** [comment]
Yes, I've solved this way. However this should be specified in documentation.
