### ISSUE TITLE
I get this error on 2.4.0 version

### ISSUE THREAD

**Issue by kruteev** [officert/vue-slideout-panel#48]
I get this error on 2.4.0 version
<img width="1913" alt="Снимок экрана 2019-10-14 в 16 43 41" src="https://user-images.githubusercontent.com/5311779/66757375-baf24e80-eea4-11e9-8a9c-e0afa0090ff6.png">

_Originally posted by @kruteev in https://github.com/officert/vue-slideout-panel/issues/25#issuecomment-541697984_

**Comment by kruteev** [comment]
absolutely!
panel opened - class good
open sweetalert toast - class good
close panel (sweetalert toast opened) - fail (class panel in <body> left but 2 classes stuck together)

**Comment by officert** [comment]
@kruteev fixed in 2.5.0
