### ISSUE TITLE
Close callback? 

### ISSUE THREAD

**Issue by kaleidotech** [officert/vue-slideout-panel#49]
How to listen on a close? Basically I'd need an action done after the slideout is closed.

**Comment by officert** [comment]
`$showPanel()` returns a `PanelInstance` object which has a `promise` property:

```js
const panelInstance = this.$showPanel({
  component : 'your-component-name',
  props: {
    //any data you want passed to your component
  }
});

panelInstance.promise
.then(result => {

});
```

https://vue2-slideout-panel.wrkflows.io/en/articles/1008
