### ISSUE TITLE
Close on mobile

### ISSUE THREAD

**Issue by razbakov** [officert/vue-slideout-panel#5]
It is not possible to close the panel on mobile device.
I would suggest to add slide event to hide it

**Comment by officert** [comment]
@razbakov I see what you mean, there's no close button for panels and the only way to close them is hitting the ESC key or clicking on the backdrop, which isn't visible on mobile. There are a couple options I'm thinking about:

1) adding a close button, like an 'X', inside the panel along the top, which could close it - downside of this option is that sometimes you might not want this 'X' button showing up in your panels
2) adding touch support for gestures like swipping left or right (probably using https://github.com/vuejs/vue-touch) - downside of this option is now the project has a dependency

Would love to get some feedback from anyone 👍

**Comment by ChadTaljaardt** [comment]
Both options should be implemented in my opinion.
