### ISSUE TITLE
When opening multiple panels backdrop does not move higher

### ISSUE THREAD

**Issue by kruteev** [officert/vue-slideout-panel#50]
When opening multiple panels backdrop does not move higher.
As a result, the panel is superimposed on the panel.
<img width="1913" alt="Снимок экрана 2019-10-15 в 16 53 37" src="https://user-images.githubusercontent.com/5311779/66837843-5b5f7600-ef6c-11e9-93d1-d837f411bf8f.png">

**Comment by kruteev** [comment]
> @kruteev yea it's really not meant for stacking panels of different sizes. I don't want to add additional backdrop unless we can do it in a way where they don't cover the ones below it, making them darker.

you can just change the z-index background 1 higher and lower it when closing

**Comment by korpow** [comment]
I just ran into this issue myself while trying to get fancy with a narrow panel opening on top of an already opened wider one.

> you can just change the z-index backdrop 1 higher and lower it when closing
@kruteev yeah that seems to be the case from messing around with the styles, nice catch.

**Comment by officert** [comment]
This is fixed in the latest versions.
