### ISSUE TITLE
Continue with Vue Pages while modal is open

### ISSUE THREAD

**Issue by erkanatesli** [officert/vue-slideout-panel#52]
Could there be made a property that we still can make use of the Vue Application while modal is open? Now when i click outside the modal the Modal closes.  It should be both open and clickable.

**Comment by officert** [comment]
@erkanatesli added in v2.8.0 : https://github.com/officert/vue-slideout-panel/releases/tag/2.8.0

**Comment by officert** [comment]
Take a look at the updated docs here: https://officert.github.io/vue-slideout-panel/#/options

`removeBg` is the option you want.
