### ISSUE TITLE
Cannot read property 'disableEscClick' of undefined

### ISSUE THREAD

**Issue by fdaprano** [officert/vue-slideout-panel#54]
I'm using vue-slideout-panel ^2.5 with Nuxt.js, imported as plugin and placed on the default layout:
`<slideout-panel></slideout-panel>`

When I press the ESC key and the panel is not visible I get the following error:

Uncaught TypeError: Cannot read property 'disableEscClick' of undefined
    at VueComponent.onEscapeKeypress (index.vue?./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options:170)

Looks like there is no check whether the panel is actually existing in this method: 
```
onEscapeKeypress: function onEscapeKeypress(e) {
      if (e.keyCode === 27) {
        var currentPanel = this.panels[this.panels.length - 1];

        if (currentPanel.disableEscClick) {
          return;
        }

        this.closeCurrentPanel({
          closedBy: 'esc'
        });
      }
    }
```
Or I'm doing something wrong?

**Comment by officert** [comment]
@fdaprano thanks! yea looks like the method just needs a check. But curious what you're doing when you get this error? Do you see a panel on the screen? Are you clicking multiple times?

**Comment by fdaprano** [comment]
@officert thanks for your answer. This bug consistently reproduces when I press ESC key and the panel is hidden.
E.g.: 
1. application starts, panel is hidden, press ESC, the error pops.
2. application starts, call $showPanel, panel shows, press ESC, panel hides, press ESC again, the error pops.

My specific condition is that I am using Nuxt.js and I placed the panel component on the default layout (inherited by all pages where I want to display a slideout) so it can be globally opened by any other component in my application.

**Comment by officert** [comment]
@fdaprano can you try v2.4.0? Should be fixed, I added to this line:

https://github.com/officert/vue-slideout-panel/blob/master/src/components/SlideoutPanel/index.vue#L194

**Comment by fdaprano** [comment]
Thanks @officert, I checked out v2.8.0 and I confirm it's fixed.
