### ISSUE TITLE
Please check the main of package.json

### ISSUE THREAD

**Issue by lbnsina** [officert/vue-slideout-panel#56]
Hello.

Thank you for your module.
It is really helpful!

But, jsut recently I got an Error that dependency has not found.
```
bootstrap.js (mine)
import VueSlideoutPanel from 'vue2-slideout-panel';
(Error: Can't not find dependency)
```

pacakge.json seems cause that issue I think.
After checking your commits, I found filename has changed like below.
(title : update docs / url : https://github.com/officert/vue-slideout-panel/commit/3f6754502e87e39a5c41649cc239a372225df2b0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
```
build/webpack.dist.js
-   filename: options.isProduction ? 'vue2-slideout-panel.min.js' : 'vue2-slideout-panel.js',
+   filename: options.isProduction ? 'vue-slideout-panel.min.js' : 'vue-slideout-panel.js',
```

Below has worked for me.
Could you let me know if I get wrong?
```
package.json
"main": "dist/vue2-slideout-panel.js",
>> "main": "dist/vue-slideout-panel.js", (Isn't it should be like this?)
```

Best Regards.

**Comment by officert** [comment]
Thanks @lbnsina just updated the package.json and release v2.7.0
