### ISSUE TITLE
Panel jiggles slighly after open

### ISSUE THREAD

**Issue by Rodigee** [officert/vue-slideout-panel#59]
![open panel jiggle](https://user-images.githubusercontent.com/33212609/78039488-cabafd80-7333-11ea-825e-5148c7c71cbe.gif)

There's a slight continuation of the opening of the panel (or jiggle) after opening the panel initially.

This is happening in Chrome and Edge on a Mac.

**Comment by officert** [comment]
@Rodigee I've noticed this too, but I have no idea what's causing it. Here's the CSS for the animation:

https://github.com/officert/vue-slideout-panel/blob/master/src/components/SlideoutPanel/styles.less#L63

**Comment by robbersite** [comment]
> ![open panel jiggle](https://user-images.githubusercontent.com/33212609/78039488-cabafd80-7333-11ea-825e-5148c7c71cbe.gif)
> 
> There's a slight continuation of the opening of the panel (or jiggle) after opening the panel initially.
> 
> This is happening in Chrome and Edge on a Mac.

这个问题，你解决了么？我也想解决。
Have you solved this problem? I also want to solve it. @Rodigee

**Comment by robbersite** [comment]
![微信图片_20200713195329](https://user-images.githubusercontent.com/23724538/87301675-9960e900-c542-11ea-982f-1d04a8a5da97.png)
==
I probably know it's here that affects the problem, but I don't know how to change it.
我大概知道是这里影响了问题，但是我不知道怎么改。

**Comment by ttjordan81** [comment]
Thanks for the package, and I saw the same thing, then saw this there was an issues already created.

After trying different CSS properties, finally came to one that seems to work. Looks a bit smoother...

.slideout-panel .slideout-wrapper .slideout {
    transition-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
    transition-duration: 0.8s;
}

**Comment by officert** [comment]
Fixed in 2.13.0 thanks to @ttjordan81 👍
