### ISSUE TITLE
Allow panel creation without backdrop

### ISSUE THREAD

**Issue by Morgul** [officert/vue-slideout-panel#6]
It would be nice if there was an option to disable the backdrop when creating a panel. I have a use case where I want to have tool options in the panel, but let them still interact with the main content of the page.

**Comment by officert** [comment]
thanks @Morgul good suggestion! I've added support by passing in `hideBg: true` in the panel options. Released new V0.10.0. You can find all the options at the bottom of the docs site: https://officert.github.io/vue-slideout-panel/#/home
https://github.com/officert/vue-slideout-panel/releases/tag/0.10.0
