### ISSUE TITLE
Scrolls to the bottom on open

### ISSUE THREAD

**Issue by phillipstemann** [officert/vue-slideout-panel#62]
Hi!

Thanks a lot for the library, it's awesome!
I have one issue though. When I have a long list of elements which I can open in the slideout. It opens the slideout and scrolls the background to the bottom. Do you have any idea what it might be? I've tried tweaking the CSS without luck.

I'm using it with NuxtJS, and is registering as a plugin, like this:
```
import Vue from 'vue'
import VueSlideoutPanel from 'vue2-slideout-panel'
Vue.use(VueSlideoutPanel)
import Task from '../components/task.vue'
Vue.component('task', Task)
```

**Comment by officert** [comment]
Sounds like something in your component. You can see a long panel in this example and it doesn't scroll to the bottom : https://officert.github.io/vue-slideout-panel/#/examples/open-on

Maybe paste your component here for us to checkout?

**Comment by phillipstemann** [comment]
Hi, yea you're right, I fixed it, it was a CSS issue. Thank you.
