### ISSUE TITLE
Provide a Slot Instead of Requiring a Globally Registered Component

### ISSUE THREAD

**Issue by ksidibe** [officert/vue-slideout-panel#63]
First nice work.
But, it could be even better if:
1. **This is implemented as a component rather than a plugin.**
2. **You provide a slot and let the user define the content of the panel instead of requiring a globally registered component.**
Thank you.

**Comment by juanvillegas** [comment]
I second this. Plus, as it is now, the inner component is always aware of the SlideOut component, which creates a very troubling dependency. The subcomponent shouldn't need to be aware of whether it was included in a slide out or a modal or just inline in the page.
Example: if my subcomponent wants to communicate upwards, the only way to do it is through the closePanel event.

**Comment by officert** [comment]
this `$showPanel` method's `component` param can either be a String or an Object. The String is assumed to be a globally registered component, the object an inline component:

```js
const MyComponent = new Vue();

const panel1Handle = this.$showPanel({
      component : MyComponent,
      props: {
        //any data you want passed to your component
      }
})
```

**Comment by officert** [comment]
@juanvillegas You can always use a wrapper component as the one you pass to `$showPanel`. This wrapper component can deal with translating from your real component to the SlideOut component (via `closePanel`). This allows your "real" component to stay cleaner and not deal with knowing anything about how it's used (via SlideOut or inline etc..)

It's not ideal but I use it this way to deal with the exact problem you brought up. Sometimes I have component used in both the SlideOut and in other places so I want to keep it from knowing anything about the SlideOut component.
But on simple components that I know will only ever live in the SlideOut panel I skip the extra wrapping component and just lets it be dependent on SlideOut.
