### ISSUE TITLE
Hiding animation of bottom mode

### ISSUE THREAD

**Issue by clintnetwork** [officert/vue-slideout-panel#67]
Hi,

I use the `openOn` bottom mode and the hide process does not have the same animation, the hide effect is a simple fading instead of a sliding effect.

I use this to close the panel:
```
this.$emit("closePanel", {});
```

Thank you

**Comment by clintnetwork** [comment]
cc @officert

**Comment by rlam3** [comment]
@clintnetwork were you able to find a workaround solution?

**Comment by officert** [comment]
@clintnetwork and @rlam3 latest versions fixes this issue

**Comment by imclint21** [comment]
Wow perfect
